### ISSUE TITLE
Not easily reproducible

### ISSUE THREAD

**Issue by wisammechano** [mamonraab/violance-detection-in-video-with-pytroch#1]
This is a nice tutorial however it isn't easily reproducible for someone to follow. Imports and definition should be laid out clearly somewhere (in both this and the Arabic version)

One example is the function called resize, is it self defined resize function? is it cv2.resize? if it is the latter then the signature doesn't match.

Overall, nice problem statement and definition, but I just feel more elements needs to be laid out for someone to follow (or perhaps a working code repo)

**Comment by mamonraab** [comment]
thank you  , i cant improve without feedback i notced your feedback and i will  update it soon  , what i tried to foucs with things that messing in pytorch document or stackoverflow  , while things that easly implment or need intermidate coding skill was not in my list  >>> overall i will   do my best to improve it further 

regards
